# Generated by Django 2.0.6 on 2018-07-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='birthday_vouchers',
            field=models.ManyToManyField(blank=True, related_name='membership_birthday', to='app01.Voucher'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='complimentary_vouchers',
            field=models.ManyToManyField(blank=True, related_name='membership_compliment', to='app01.Voucher'),
        ),
    ]
