# Generated by Django 2.0.6 on 2018-07-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180725_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='memberships',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='app01.Membership'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='occupations',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='app01.Occupation'),
        ),
        migrations.AlterField(
            model_name='campaigncondition',
            name='every_purchase_l_drinks_flavors',
            field=models.ManyToManyField(blank=True, related_name='l_drinks_condition', to='app01.Product'),
        ),
        migrations.AlterField(
            model_name='campaigncondition',
            name='every_purchase_m_drinks_flavors',
            field=models.ManyToManyField(blank=True, related_name='m_drinks_condition', to='app01.Product'),
        ),
        migrations.AlterField(
            model_name='campaigncondition',
            name='every_purchase_products',
            field=models.ManyToManyField(blank=True, related_name='products_condition', to='app01.Product'),
        ),
        migrations.AlterField(
            model_name='campaigntype',
            name='free_vouchers',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='app01.Voucher'),
        ),
        migrations.AlterField(
            model_name='member',
            name='campaigntypes',
            field=models.ManyToManyField(blank=True, related_name='members', through='app01.Member_CampaignType', to='app01.CampaignType'),
        ),
        migrations.AlterField(
            model_name='member',
            name='interestGroups',
            field=models.ManyToManyField(blank=True, related_name='members', to='app01.InterestGroup'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='campaigns',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='app01.Campaign'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='campaigntypes',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='app01.CampaignType'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='redeemed_vouchers',
            field=models.ManyToManyField(blank=True, related_name='transaction_redeemed', to='app01.Voucher'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reward_vouchers',
            field=models.ManyToManyField(blank=True, related_name='transaction_reward', to='app01.Voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_per_unparticipated_products',
            field=models.ManyToManyField(blank=True, related_name='vouchers_discount_per', to='app01.Product'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_price_unparticipated_products',
            field=models.ManyToManyField(blank=True, related_name='vouchers_discount_price', to='app01.Product'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='limit_memberships',
            field=models.ManyToManyField(blank=True, related_name='vouchers', to='app01.Membership'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='redemption_products',
            field=models.ManyToManyField(blank=True, related_name='vouchers_redemption', to='app01.Product'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='redemption_toppings',
            field=models.ManyToManyField(blank=True, related_name='vouchers', to='app01.Toppings'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='size_upgrade_unparticipated_products',
            field=models.ManyToManyField(blank=True, related_name='vouchers_upgrade', to='app01.Product'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='toppings_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='toppings_number'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='unparticipated_outlets',
            field=models.ManyToManyField(blank=True, related_name='vouchers', to='app01.Outlet'),
        ),
    ]
