# Generated by Django 2.0.6 on 2018-07-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180725_1339'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='member',
            name='mobile_no_idx',
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_no',
            field=models.CharField(max_length=64, verbose_name='mobile_no'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
    ]
