# Generated by Django 2.0.6 on 2018-07-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_emailverifyrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
    ]
