# Generated by Django 2.0.6 on 2018-07-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20180725_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile_no',
            field=models.CharField(max_length=64, unique=True, verbose_name='mobile_no'),
        ),
    ]
