# Generated by Django 2.0.6 on 2018-07-27 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_emailverifyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, unique=True, verbose_name='邮箱')),
                ('session', models.CharField(blank=True, max_length=32, unique=True, verbose_name='登录码')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间')),
            ],
        ),
    ]
