# Generated by Django 2.0.6 on 2018-07-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_loginsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsession',
            name='id',
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='email',
            field=models.EmailField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='邮箱'),
        ),
    ]
