# Generated by Django 2.0.6 on 2018-07-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20180727_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nick_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NickName'),
        ),
    ]
